// network/dnsconfig.js

var REG_NONE = NewRegistrar("none");
var CF = NewDnsProvider("cloudflare");

var PROVIDERS = {
  "cloudflare": CF,
  "none": REG_NONE
};

// Map string names to the actual DNSControl functions
var RECORD_TYPES = {
  "A": A,
  "AAAA": AAAA,
  "CNAME": CNAME,
  "TXT": TXT,
  "MX": MX,
  "NS": NS,
  "SRV": SRV,
  "CAA": CAA
};

// Load the JSON file generated by the deploy script
var config = require("network/dns_zones.json");

for (var domainName in config.domains) {
  var domainData = config.domains[domainName];
  var records = [];

  if (domainData.records) {
    for (var i = 0; i < domainData.records.length; i++) {
      var r = domainData.records[i];
      var modifiers = [];
      
      // Cloudflare Proxy Toggle
      if (r.proxied === true) modifiers.push(CF_PROXY_ON);
      if (r.proxied === false) modifiers.push(CF_PROXY_OFF);

      // Find the correct function for this record type
      var recordFunc = RECORD_TYPES[r.type];
      if (!recordFunc) {
        throw new Error("Unknown or unsupported record type: " + r.type);
      }

      // We must spread the arguments using .apply() so 'modifiers' is passed as individual arguments, not as a single array argument.
      var args = [r.name, r.target].concat(modifiers);
      records.push(recordFunc.apply(null, args));
    }
  }

  D(domainName, 
    REG_NONE, 
    DnsProvider(PROVIDERS[domainData.provider]), 
    records
  );
}